---
- hosts: all
  ignore_errors: yes
  become: yes
  tasks:
    - name: Upgrade all packages
      yum: 
        name: '*'
        state: latest
      when: ansible_distribution == "Centos"
    - name: Upgrade the OS
      apt:
        upgrade: dist 
        update_cache: yes
      when: ansible_distribution == "Ubuntu"
    - name: Reboot
      reboot:
